apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 575418475462.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 575418475462.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: f338790b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
